
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 25 2023 13:38:18 +07 (Mar 25 2023 06:38:18 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clock, reset, led_out, flick);
  input clock, reset, flick;
  output [15:0] led_out;
  wire clock, reset, flick;
  wire [15:0] led_out;
  wire [2:0] state_next;
  wire [15:0] tmpLed;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_5,
       n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_24, n_25, n_26, n_45;
  wire n_51, n_52, n_53, n_62, n_63, n_66, n_71, n_73;
  wire n_74, n_75, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_85, n_86, n_87, n_88, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_99, n_429, n_431, n_441, n_442, n_798;
  wire n_803, n_835, n_836, n_843, n_844, n_846, n_847, n_848;
  wire n_849, n_852, n_853, n_893, n_894, n_895, n_896, n_899;
  wire n_900, n_905, n_907, n_909, n_910, n_911, n_912, n_913;
  wire n_916, n_917, n_918, n_919, n_921, n_922, n_923, n_928;
  wire n_932, n_933, n_934, n_936, n_953, n_970, n_971, n_972;
  wire n_973, n_974, n_975, n_976, n_977, n_978, n_1042, n_1043;
  wire n_1044, n_1045, n_1052, n_1053, n_1054, n_1065, n_1066;
  TLATNXL \state_next_reg[1] (.GN (n_92), .D (n_95), .Q
       (state_next[1]), .QN (UNCONNECTED));
  OAI211X1 g1966__2398(.A0 (n_93), .A1 (n_63), .B0 (n_85), .C0 (n_94),
       .Y (n_95));
  AOI32X1 g1968__5107(.A0 (led_out[5]), .A1 (n_80), .A2 (n_932), .B0
       (n_93), .B1 (n_90), .Y (n_94));
  DFFRHQX4 \led_out_reg[14] (.RN (n_99), .CK (clock), .D (tmpLed[14]),
       .Q (led_out[14]));
  TLATNXL \state_next_reg[0] (.GN (n_92), .D (n_91), .Q
       (state_next[0]), .QN (UNCONNECTED0));
  DFFHQX1 \tmpLed_reg[14] (.CK (clock), .D (n_836), .Q (tmpLed[14]));
  OR2X1 g1970__6260(.A (n_88), .B (n_86), .Y (n_91));
  OAI33X1 g1974__4319(.A0 (flick), .A1 (n_82), .A2 (n_87), .B0
       (led_out[6]), .B1 (n_25), .B2 (n_24), .Y (n_90));
  OAI32X1 g1972__8428(.A0 (led_out[15]), .A1 (flick), .A2 (n_87), .B0
       (led_out[5]), .B1 (n_6), .Y (n_88));
  OAI211X1 g1973__5526(.A0 (n_62), .A1 (n_85), .B0 (n_53), .C0 (n_81),
       .Y (n_86));
  DFFRHQX4 \led_out_reg[7] (.RN (n_99), .CK (clock), .D (tmpLed[7]), .Q
       (led_out[7]));
  DFFRHQX4 \led_out_reg[3] (.RN (n_99), .CK (clock), .D (tmpLed[3]), .Q
       (led_out[3]));
  DFFRHQX4 \led_out_reg[9] (.RN (n_99), .CK (clock), .D (tmpLed[9]), .Q
       (led_out[9]));
  DFFRHQX4 \led_out_reg[12] (.RN (n_99), .CK (clock), .D (tmpLed[12]),
       .Q (led_out[12]));
  DFFRHQX4 \led_out_reg[6] (.RN (n_99), .CK (clock), .D (tmpLed[6]), .Q
       (led_out[6]));
  DFFRHQX4 \led_out_reg[10] (.RN (n_99), .CK (clock), .D (tmpLed[10]),
       .Q (led_out[10]));
  DFFRHQX4 \led_out_reg[4] (.RN (n_99), .CK (clock), .D (tmpLed[4]), .Q
       (led_out[4]));
  DFFRHQX4 \led_out_reg[2] (.RN (n_99), .CK (clock), .D (tmpLed[2]), .Q
       (led_out[2]));
  DFFRHQX4 \led_out_reg[11] (.RN (n_99), .CK (clock), .D (tmpLed[11]),
       .Q (led_out[11]));
  DFFRHQX4 \led_out_reg[5] (.RN (n_99), .CK (clock), .D (tmpLed[5]), .Q
       (led_out[5]));
  DFFHQX1 \tmpLed_reg[6] (.CK (clock), .D (n_78), .Q (tmpLed[6]));
  DFFHQX1 \tmpLed_reg[13] (.CK (clock), .D (n_847), .Q (tmpLed[13]));
  DFFHQX1 \tmpLed_reg[10] (.CK (clock), .D (n_71), .Q (tmpLed[10]));
  DFFHQX1 \tmpLed_reg[7] (.CK (clock), .D (n_835), .Q (tmpLed[7]));
  DFFHQX1 \tmpLed_reg[8] (.CK (clock), .D (n_849), .Q (tmpLed[8]));
  DFFHQX1 \tmpLed_reg[9] (.CK (clock), .D (n_1054), .Q (tmpLed[9]));
  INVXL g2005(.A (led_out[15]), .Y (n_82));
  DFFHQX1 \tmpLed_reg[1] (.CK (clock), .D (n_73), .Q (tmpLed[1]));
  DFFHQX1 \tmpLed_reg[12] (.CK (clock), .D (n_844), .Q (tmpLed[12]));
  DFFHQX1 \tmpLed_reg[5] (.CK (clock), .D (n_928), .Q (tmpLed[5]));
  DFFHQX1 \tmpLed_reg[2] (.CK (clock), .D (n_77), .Q (tmpLed[2]));
  DFFHQX1 \tmpLed_reg[3] (.CK (clock), .D (n_79), .Q (tmpLed[3]));
  DFFHQX1 \tmpLed_reg[4] (.CK (clock), .D (n_75), .Q (tmpLed[4]));
  DFFHQX1 \tmpLed_reg[11] (.CK (clock), .D (n_74), .Q (tmpLed[11]));
  DFFRHQX4 \led_out_reg[15] (.RN (n_99), .CK (clock), .D (tmpLed[15]),
       .Q (led_out[15]));
  TLATNXL \state_next_reg[2] (.GN (n_92), .D (n_66), .Q
       (state_next[2]), .QN (UNCONNECTED1));
  AOI21XL g2002__3680(.A0 (n_80), .A1 (n_45), .B0 (n_26), .Y (n_81));
  OAI211X1 g2008__1617(.A0 (n_52), .A1 (n_11), .B0 (n_5), .C0 (n_87),
       .Y (n_66));
  DFFHQX1 \tmpLed_reg[0] (.CK (clock), .D (n_918), .Q (tmpLed[0]));
  DFFHQX1 \tmpLed_reg[15] (.CK (clock), .D (n_905), .Q (tmpLed[15]));
  AOI22XL g2038__1705(.A0 (n_99), .A1 (n_9), .B0 (n_62), .B1 (n_51), .Y
       (n_63));
  AOI33XL g2031__6161(.A0 (n_52), .A1 (state_next[1]), .A2 (n_10), .B0
       (flick), .B1 (n_51), .B2 (n_932), .Y (n_53));
  NAND2XL g2035__2346(.A (n_12), .B (n_933), .Y (n_45));
  AOI2BB1X1 g2057__5526(.A0N (n_25), .A1N (state_next[2]), .B0 (n_24),
       .Y (n_26));
  AOI32X1 g2055__6131(.A0 (led_out[6]), .A1 (state_next[1]), .A2
       (n_52), .B0 (n_25), .B1 (n_932), .Y (n_12));
  NAND2XL g2068__1881(.A (n_10), .B (state_next[1]), .Y (n_11));
  AOI2BB1X1 g2059__7482(.A0N (flick), .A1N (n_52), .B0 (state_next[2]),
       .Y (n_9));
  AOI211XL g2062__4733(.A0 (led_out[4]), .A1 (n_25), .B0 (n_933), .C0
       (n_7), .Y (n_92));
  NAND3BXL g2067__6161(.AN (n_7), .B (flick), .C (n_52), .Y (n_24));
  NAND2XL g2071__9315(.A (state_next[2]), .B (n_80), .Y (n_87));
  NAND3BXL g2064__2883(.AN (state_next[1]), .B (state_next[2]), .C
       (n_51), .Y (n_6));
  OAI211X1 g2060__2346(.A0 (n_62), .A1 (n_93), .B0 (n_99), .C0
       (state_next[2]), .Y (n_5));
  NOR2XL g2069__1666(.A (flick), .B (n_7), .Y (n_10));
  NAND3BXL g2061__5477(.AN (state_next[2]), .B (state_next[1]), .C
       (n_51), .Y (n_85));
  INVXL g2072(.A (n_7), .Y (n_80));
  NAND2XL g2074__5107(.A (n_99), .B (state_next[0]), .Y (n_7));
  NAND2BXL g2077__6260(.AN (led_out[11]), .B (led_out[10]), .Y (n_52));
  NOR2XL g2076__4319(.A (reset), .B (state_next[0]), .Y (n_51));
  BUFX2 g2084(.A (led_out[0]), .Y (n_62));
  BUFX2 g2080(.A (led_out[1]), .Y (n_0));
  INVXL g2094(.A (led_out[5]), .Y (n_25));
  INVXL g2093(.A (state_next[1]), .Y (n_93));
  NAND2X4 g2140__3680(.A (n_953), .B (n_917), .Y (n_78));
  NAND2X4 g2144__2802(.A (n_922), .B (n_894), .Y (n_71));
  NAND2X4 g2152__7098(.A (n_916), .B (n_896), .Y (n_73));
  NAND2X4 g2160__7482(.A (n_899), .B (n_911), .Y (n_79));
  NAND2X4 g2162__4733(.A (n_893), .B (n_907), .Y (n_75));
  NAND2X4 g2164__6161(.A (n_921), .B (n_852), .Y (n_74));
  DFFRHQX4 \led_out_reg[1] (.RN (n_99), .CK (clock), .D (tmpLed[1]), .Q
       (led_out[1]));
  NOR3X4 g22(.A (n_932), .B (reset), .C (n_441), .Y (n_442));
  INVX2 g2848(.A (led_out[6]), .Y (n_803));
  OAI22X4 g31(.A0 (n_803), .A1 (n_923), .B0 (n_798), .B1 (n_900), .Y
       (n_835));
  OAI31X4 g23(.A0 (n_429), .A1 (reset), .A2 (n_431), .B0 (n_936), .Y
       (n_836));
  NAND2X4 g2866(.A (n_843), .B (n_910), .Y (n_844));
  NAND2X4 g2869(.A (n_846), .B (n_909), .Y (n_847));
  NAND2X4 g15(.A (n_848), .B (n_912), .Y (n_849));
  NAND2X6 g2871(.A (led_out[12]), .B (n_1045), .Y (n_852));
  DFFRX2 \led_out_reg[8] (.RN (n_99), .CK (clock), .D (tmpLed[8]), .Q
       (led_out[8]), .QN (n_798));
  NAND2X6 g2884(.A (led_out[14]), .B (n_1045), .Y (n_846));
  NAND2X6 g2886(.A (led_out[13]), .B (n_1045), .Y (n_843));
  NAND2X6 g2890(.A (led_out[9]), .B (n_1045), .Y (n_848));
  NAND2X6 g2892(.A (led_out[10]), .B (n_1045), .Y (n_853));
  NAND2X6 g2027__2928(.A (led_out[5]), .B (n_1066), .Y (n_893));
  NAND2X4 g2931(.A (led_out[11]), .B (n_1066), .Y (n_894));
  NAND2X4 g2933(.A (led_out[2]), .B (n_1066), .Y (n_896));
  NAND2X4 g2026__2935(.A (led_out[4]), .B (n_1043), .Y (n_899));
  CLKINVX4 g2936(.A (n_1043), .Y (n_900));
  CLKAND2X2 g2042__2941(.A (led_out[14]), .B (n_976), .Y (n_905));
  NAND2X4 g2041__2943(.A (led_out[3]), .B (n_976), .Y (n_907));
  NAND2X4 g2040__2944(.A (led_out[12]), .B (n_977), .Y (n_909));
  NAND2X4 g2046__2945(.A (led_out[11]), .B (n_977), .Y (n_910));
  NAND2X4 g2047__2946(.A (led_out[2]), .B (n_977), .Y (n_911));
  NAND2X4 g2043__2947(.A (led_out[7]), .B (n_977), .Y (n_912));
  AND2X1 g2948(.A (state_next[0]), .B (n_933), .Y (n_913));
  NAND2X4 g2949(.A (led_out[0]), .B (n_978), .Y (n_916));
  NAND2X4 g2053__2952(.A (led_out[5]), .B (n_978), .Y (n_917));
  OR2X4 g2056__2953(.A (n_978), .B (n_442), .Y (n_918));
  NAND2X4 g2048__2954(.A (n_0), .B (n_978), .Y (n_919));
  NAND2X4 g2052__2955(.A (led_out[10]), .B (n_971), .Y (n_921));
  NAND2X4 g2049__2956(.A (led_out[9]), .B (n_971), .Y (n_922));
  CLKINVX6 g2957(.A (n_971), .Y (n_923));
  NAND2X2 g41(.A (n_972), .B (n_974), .Y (n_928));
  NAND3X6 g2962(.A (led_out[15]), .B (n_934), .C (n_99), .Y (n_936));
  OAI21X2 g2963(.A0 (state_next[0]), .A1 (n_932), .B0 (n_933), .Y
       (n_934));
  NOR2XL g2964(.A (state_next[2]), .B (state_next[1]), .Y (n_932));
  NAND2XL g2965(.A (state_next[1]), .B (state_next[2]), .Y (n_933));
  INVX6 g2966(.A (reset), .Y (n_99));
  NAND2X4 g6(.A (led_out[7]), .B (n_1043), .Y (n_953));
  CLKAND2X12 g2924_dup2986(.A (n_913), .B (n_970), .Y (n_971));
  INVX16 fopt2987(.A (reset), .Y (n_970));
  NAND3X4 g2988(.A (led_out[6]), .B (n_934), .C (n_970), .Y (n_972));
  NAND3X4 g2989(.A (n_913), .B (led_out[4]), .C (n_973), .Y (n_974));
  CLKINVX20 g2990(.A (reset), .Y (n_973));
  CLKAND2X6 g2991(.A (n_913), .B (n_975), .Y (n_976));
  CLKINVX16 g2815_dup2992(.A (reset), .Y (n_975));
  CLKAND2X12 g2926_dup2993(.A (n_913), .B (n_975), .Y (n_977));
  CLKAND2X12 g2994(.A (n_913), .B (n_973), .Y (n_978));
  DFFRX4 \led_out_reg[0] (.RN (n_99), .CK (clock), .D (tmpLed[0]), .Q
       (led_out[0]), .QN (UNCONNECTED2));
  CLKAND2X12 g2847_dup3035(.A (n_934), .B (n_1042), .Y (n_1043));
  CLKINVX8 fopt3036(.A (reset), .Y (n_1042));
  CLKAND2X12 g3037(.A (n_934), .B (n_1044), .Y (n_1045));
  CLKINVX16 fopt2982_dup(.A (reset), .Y (n_1044));
  NAND2X4 g11(.A (n_1053), .B (n_853), .Y (n_1054));
  NAND2X6 g12(.A (n_1052), .B (n_976), .Y (n_1053));
  BUFX3 g3040(.A (led_out[8]), .Y (n_1052));
  NOR2X8 g7(.A (n_1065), .B (reset), .Y (n_1066));
  INVXL g8(.A (n_934), .Y (n_1065));
  DFFRX4 \led_out_reg[13] (.RN (n_99), .CK (clock), .D (tmpLed[13]), .Q
       (led_out[13]), .QN (n_431));
  INVX3 g3049(.A (led_out[1]), .Y (n_441));
  INVX1 g3051(.A (n_913), .Y (n_429));
  NAND2X4 g3053(.A (led_out[3]), .B (n_1066), .Y (n_895));
  NAND2X2 g2158__3055(.A (n_895), .B (n_919), .Y (n_77));
endmodule

